name: Build APK with Buildozer

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        sudo apt update
        sudo apt install -y build-essential git zip unzip openjdk-17-jdk python3-pip
        pip install buildozer

    - name: Build APK
      run: buildozer --verbose android debug

    - name: List bin directory
      run: ls -l bin/

    - name: Find APK files
      run: find . -name "*.apk"

    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
        name: lifi-apk
        path: bin/*.apk

